baseURL = "https://andreaellery.netlify.app/"
languageCode = "en-us"
[[menu.main]]
name = "Login"
url = "https://www.idxhome.com/organizer/login/145641"
weight = 5
[[menu.main]]
name = "Search Homes"
url = "https://www.idxhome.com/homesearch/145641"
weight = 4
[[menu.main]]
name = "Testimonials"
parent = "About"
url = "/testimonials"
weight = 3
[[menu.main]]
name = "Our Team"
parent = "About"
url = "/teams"
weight = 2
[[menu.main]]
name = "About"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
status = "status"
tag = "tags"
