baseURL = "/"
languageCode = "en-us"
[[menu.main]]
name = "Our Partners"
parent = "Corinne"
url = "/partners"
weight = 2
[[menu.main]]
name = "Our Team"
parent = "Corinne"
url = "/teams"
weight = 1
[[menu.main]]
name = "Listings"
url = "/listings"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
status = "status"
tag = "tags"
