baseURL = "https://andreaellery.netlify.app/"
languageCode = "en-us"
[[menu.main]]
name = "Testimonials"
parent = "Resources"
url = "/testimonials"
weight = 3
[[menu.main]]
name = "Our Team"
parent = "Resources"
url = "/teams"
weight = 2
[[menu.main]]
name = "Our Partners"
parent = "Resources"
url = "/partners"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Search Homes"
url = "https://www.idxhome.com/homesearch/145641"
weight = 2
[[menu.main]]
name = "Resources"
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[taxonomies]
category = "categories"
status = "status"
tag = "tags"
