---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: data/menu.yaml
  label: Menu
- type: document
  path: data/design.yaml
  label: Design
- type: heading
  label: Default Pages
- type: document
  path: data/profile.yaml
  label: My Profile
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog
- type: document
  path: content/testimonials/testimonials.md
  label: Testimonials
  match: "**/*"
- type: heading
  label: Listings
- type: directory
  path: content/listings
  label: Property Listings
  create: documents
  match: "**/*"
  templates:
  - property
- type: heading
  label: Teams and Office
- type: directory
  path: content/teams
  label: Teams
  create: documents
  match: "**/*"
  templates:
  - team
- type: directory
  path: content/offices
  label: Offices
  create: documents
  match: "**/*"
  templates:
  - offices
- type: heading
  label: Partners
- type: directory
  path: content/partners
  label: Preferred Partners
  create: documents
  match: "**/*"
  templates:
  - partners
- type: heading
  label: External
- type: document
  path: content/help/links.md
  label: Quick Links
  read_only: true
- type: heading
  label: Help Center
- type: document
  path: content/help/website-editing.md
  label: Website Editing
  read_only: true
- type: document
  path: data/icons.json
  label: Developer Access Only
  read_only: true
upload_dir: ''
public_path: https://reluxurytemplate.s3-us-west-1.amazonaws.com
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
