---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Help Center
- type: document
  path: content/help/website-editing
  label: Website Editing
  read_only: true
- type: heading
  label: Teams and Office
- type: directory
  path: content/teams
  label: Teams
  create: documents
  match: "**/*"
  templates:
  - team
- type: heading
  label: Listings
- type: directory
  path: content/listings
  label: Property Listings
  create: documents
  match: "**/*"
  templates:
  - property
- type: heading
  label: Default Pages
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
