---
label: IDX Config
hide_body: true
fields:
- name: idx_id
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  label: IDX ID
- name: enable_home_quick_search
  type: boolean
  label: Enable Home Quick Search
  description: Enabling this will displays the quick search overlaying the main image.
pages:
- data/idx.yaml
